/*
 * generated by Xtext 2.10.0
 */
package dk.sdu.mmmi.sgl.tests

import com.google.inject.Inject
import dk.sdu.mmmi.sgl.spreadsheetGrammarLanguage.Grammar
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(SpreadsheetGrammarLanguageInjectorProvider)
class SpreadsheetGrammarLanguageParsingTest{

	@Inject
	ParseHelper<Grammar> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
