/*
 * generated by Xtext 2.10.0
 */
package dk.sdu.mmmi.sgl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SpreadsheetGrammarLanguageRuntimeModule extends AbstractSpreadsheetGrammarLanguageRuntimeModule {
}
